config/routes.rb
Rails.application.routes.draw do
  resources :users
  # TEM DIFERENÇA users e user como 'as: users'
  #get '/users', to: 'users#index', as: :users  # generates the path to the index action
  #get '/users/new', to: 'users#new', as: :new_user
  #post '/users', to: 'users#create', as: :create_user
  #get '/users/:id', to: 'users#show', as: :user
  #get '/users/:id/edit', to: 'users#edit', as: :edit_user
  #patch 'users/:id', to: 'users#update', as: :update_user
  #delete 'users/:id', to: 'users#destroy', as: :delete_user
  # So the syntax as: :user_path(user.id) is not valid. Instead, you can use a simple name for the named route, like user. 
  # The :as option will automatically create a named route with the _path suffix.

  # Por fim, para definir a URL é preciso entrar no arquivo routes.rb e, com o helper do Rails, todas ações padrões são mapeadas. 
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create' # to enter the system
  get 'sign_out' => 'sessions#destroy'
  root 'sessions#new'
  #new_photo_path  # generates the path to the new action
  #photo_path(:id)

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password # i want accept a senha and transform it in to a 'senha' digest and store it in the password_digest
    #Quando incluído no código, será possível salvar: Um atributo password_digest no banco, que será a senha encriptada; Os atributos virtuais, password e password_confirmation, incluindo a requisição se eles combinam; Um método authenticate que retorna o usuário quando a senha está correta. O único requerimento para funcionamento desse comportamento é a criação do campo password_digest na tabela User. Para implementar é preciso criar uma migration com o código a seguir: rails generate migration add_password_digest_to_users password_digest:string

    validates :name, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: {minimum: 6}
    VALID_EMAIL_FORMAT = URI::MailTo::EMAIL_REGEXP  # /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false} # https://stackoverflow.com/questions/690664/rails-validates-uniqueness-of-case-sensitivity
    before_save { self.email = email.downcase } # antes de salvar, vamos transformar o email em letra minúscula
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
before_action :block_access, except: [:destroy]
  def create
            @user = User.find_by(email: params[:session][:email].downcase)
            if @user && @user.authenticate(params[:session][:password])
              sign_in(@user)
              redirect_to current_user
            else
              render action: :new
            end
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new # create a new user
  end
  
  def create # will activate it in the bank and redirect it to your page, which is the action show
    @user = User.new(user_params)
    if @user.save
                redirect_to @user, notice: "Usuário foi criado com sucesso!"
                #tire o método de comentário quando criar o helper.
                #Usuário depois de cadastrar-se acessa o sistema automaticamente
    #sign_in(@user)
    else
      render action: :new
    end
  end

  private
  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
        session[:user_id] = @user.id
    end
    # A partir de agora, através desse método o usuário está logando com um cookie temporário que expira ao fechar o browser. Mas, para chamar esse método em todos os controllers é preciso incluir o helper no ApplicationController.
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def block_access
            if current_user.present?
                    redirect_to users_path
            end
    end

    def logged_in?
        !current_user.nil? # é possível checar seu status de login, ou seja, se um usuário está logado o current_user não é nil.
    end

    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav>
      <ul>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li>
            <ul>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li>
                <%= link_to "Log out", sign_out_path, method: :delete, data: { confirm: "Are you sure you want to log out?" }  %> <!--Por padrão usa o get, então precisa colocar delete-->
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", root_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JornadaDev</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1> Users </h1>
 <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to "Show", user %></td>
        </tr>
     <%end%>
   </tbody>
</table>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
            <div class="alert-error">
                O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
            </div>
            
            <ul>
                <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
                <%= f.label :name %>
                <%= f.text_field :name %>
    </div>
        <!-- Seria como isso:
        <form action="/users/1" method="post">
        <input type="hidden" name="_method" value="patch">
        <input type="text" name="user[name]" id="user_name" value="John Doe">
        </form> 
        -->
    <div class="field">
                <%= f.label :email %>
                <%= f.email_field :email %>
    </div>
    <div class="field">
                <%= f.label :password %>
                <%= f.password_field :password %>
    </div>
    <div class="field">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
                <%= f.submit "Cadastrar"%>
    </div>
    
<% end %>

app/views/users/show.html.erb
<html>
    <body>
        <h3>Perfil de <%= @user.name %> </h3>
        <%= @user.email %>
    </body>
</html>